### ISSUE TITLE
universal version

### ISSUE THREAD

**Issue by modosc** [rollbar/node_rollbar#103]
we have a universal react app. we want to catch errors inside of various react components with rollbar.

in the client i do something like:
```
Rollbar.error("Something went wrong", e)
```
but on the server i have to do something like:
```
rollbar.handleErrorWithPayloadData(e, {level: "error", custom: {message: "Something went wrong"}})
```
for now i wrote a [wrapper class](https://gist.github.com/modosc/de7f72fd7b5646029811026894b4fc91) to take care of this but i only tested it for our specific usage cases (and because of the way ordering is sometimes optional i'm sure there are plenty of cases i missed). 

are there any plans to release either a universal version of the rollbar js library or at least to use the same api across both implementations?

**Comment by rokob** [comment]
I am working on making https://github.com/rollbar/rollbar.js actually work on both the server and in the browser. The idea is to unify the APIs to handle this issue. The tracking issue for this work is: #248
