### ISSUE TITLE
extractIp logic is broken

### ISSUE THREAD

**Issue by lehresman** [rollbar/node_rollbar#104]
Reported by @modosc on the rollbar.js repo, but I believe this is actually a node_rollbar issue:

"all of our exceptions show request.user_ip to be a non-routable address - this is because external connections bounce through several layers of AWS infrastructure. we can get the correct client ip address with request-ip though - would you be open to a pr which uses this module to replace extractIp()? alternately would it be possible to make the ip address attribute configurable (request-ip places its calculated result in req.clientIp)? happy to do either."

Original issue filed here:  https://github.com/rollbar/rollbar.js/issues/227

**Comment by lehresman** [comment]
@modosc Are you still up for submitting a PR for this?  What you suggest seems reasonable and a good approach.

**Comment by modosc** [comment]
sure, which approach seems more preferable?

**Comment by lehresman** [comment]
Using `request-ip` seems like a good approach to me.

**Comment by modosc** [comment]
pr opened.

**Comment by rokob** [comment]
Thanks @modosc for fixing this!
