### ISSUE TITLE
Request Release

### ISSUE THREAD

**Issue by SpainTrain** [rollbar/node_rollbar#116]
There have been a number of commits and new useful features since the last npm release.  In particular, we accidentally tried using the new config options and spun our wheels a bit troubleshooting why they were not working. 

Is it possible to get a new release cut with the new features?  I understand you are consolidating the js libraries (https://github.com/rollbar/rollbar.js/issues/248), but it'd be nice to use the features already added in this repo.

**Comment by rokob** [comment]
Sorry for the delay, yes I will cut a new release in the next couple days to get the new features out. I will update this issue once that happens.

**Comment by rokob** [comment]
I just pushed https://github.com/rollbar/node_rollbar/releases/tag/v0.6.4 out to npm.
