### ISSUE TITLE
0.6.4 is broken

### ISSUE THREAD

**Issue by gigafied** [rollbar/node_rollbar#118]
`uuid` is missing from dependencies.

```
Unhandled rejection Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/projects/amplifi-vision/node_modules/rollbar/lib/notifier.js:9:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/projects/amplifi-vision/node_modules/rollbar/rollbar.js:7:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

This caused us a lot of grief, not necessarily your guys fault, but we do pay for Rollbar, you should take a bit more caution in testing and publishing new releases.

**Comment by brianr** [comment]
Thanks @gigafied and sorry for the trouble - we're looking into this now and figuring out why it didn't break anything in the test suite.

**Comment by rokob** [comment]
I am a bit at a loss, `uuid` is listed in the dependencies, we are importing it as the uuid docs specify and as makes sense with their code, and it is installed in the node_modules directory when npm install is run with the updated rollbar dependency. I tried this on a test node project that I had where I upgraded from 0.6.2 to 0.6.4, and I saw the uuid module installed as part of running `npm install`. 

Can you give me a little more information about your local setup? Is uuid in your node_modules or is node-uuid? What are you running that leads to this output?

**Comment by rokob** [comment]
Note I had to run `npm update rollbar` on my project just because of the way the rollbar dependency was specified, doing that caused node-uuid to be removed and an existing version of uuid that is shared by a different dependency to be used.

**Comment by gigafied** [comment]
This might be an `npm` module resolution issue...

Running `npm ls` gives only one instance of `uuid`
```
├─┬ aws-sdk@2.26.0
│ ├─┬ buffer@4.9.1
│ │ └── base64-js@1.2.0
│ ├── crypto-browserify@1.0.9
│ ├── jmespath@0.15.0
│ ├── querystring@0.2.0
│ ├── sax@1.1.5
│ ├─┬ url@0.10.3
│ │ └── punycode@1.3.2
│ ├── uuid@3.0.0
│ ├── xml2js@0.4.15
│ └─┬ xmlbuilder@2.6.2
│   └── lodash@3.5.0
```

Specifically, if you do a require referencing a subpath, it doesn't work. Yet, if I replace `require('uuid/v4')` with `require('uiid').v4` the issue goes away.

**Comment by rokob** [comment]
Ah, the problem is we have uuid at `3.0.x` and `3.0.0` doesn't have a v4 file, it only exports v4 from the root. `3.0.1` broke out v1 and v4 into their own files. So it is our fault, it must be that some other library you have depended on 3.0.0 and then our specification didn't violate that so npm didn't install another one. Ultimately this is our fault, I will roll another release because I don't think I can change things that are already in the wild. Sorry about this.

**Comment by gigafied** [comment]
Okay, now I see what's happening... `require('uuid/v4')` is not supported in `3.0.0`, that was introduced in `3.0.1`, yet rollbar uses `3.0.x` as the version for `uuid`, `aws-sdk` on the other hand uses `3.0.0`, which also satisfies rollbar's version requirement, however that breaks since `uuid/v4` does not work on `3.0.0`

So two solutions:

- Use `require('uuid').v4`
- Use `3.0.1` for `uuid` version

https://github.com/aws/aws-sdk-js/blob/master/package.json#L44

**Comment by rokob** [comment]
👍

**Comment by cwp** [comment]
I'm seeing this too. I can confirm the 3.0.1 vs 3.0.0 issue, triggered by aws-sdk.

**Comment by rokob** [comment]
0.6.5 should be good to go, at least as it pertains to this issue. Sorry about that.
