### ISSUE TITLE
Not reporting errors to my Rollbar account

### ISSUE THREAD

**Issue by khrome83** [rollbar/node_rollbar#121]
Below is my code taken from the express example. Notice that app in this case is actually `next.js` and server is `express`. 

I created a intentional failure on `/` to test rollbar. I do not see this issue being flagged in the account, yet it is displaying on the console. I validated that the node process variables are correct, passing in my token and 'localhost'.

Is there something I need to do differently?

```
const express = require('express');
const rollbar = require('rollbar');
const next = require('next');
const config = require('./env/config');

const dev = process.env.MODE !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare()
.then(() => {
  const server = express();

  server.set('port', process.env.PORT || 3000);

  server.get('/', (req, res) => {
    req.user_id = 'test-user';
    throw new Error('Testing Node.js Enviroment');
  });

  server.get('*', (req, res) => handle(req, res));

  server.use(rollbar.errorHandler(config.ERROR_REPORTING, { environment: config.NODE_ENV }));

  server.listen(server.get('port'), (err) => {
    if (err) throw err;
    /* eslint-disable */
    console.log(`> Ready on http://localhost: ${server.get('port')}`);
    /* eslint-enable */
  });
});

```

**Comment by rokob** [comment]
> I validated that the node process variables are correct, passing in my token and 'localhost'.

Sorry I am a little confused, what do you mean by the process variables are correct and that you are passing in 'localhost'? If you hardcode the access token as a string in place of `config.ERROR_REPORTING`, do you still get the same problem?

**Comment by khrome83** [comment]
I can try that, but config.ERROR_REPORTING is a string. I just mean that the values being passed in are correct.

**Comment by rokob** [comment]
I put your exact code above into a file called `index.js` in a directory with a package.json with the following dependencies:
```js
  "dependencies": {
    "express": "^4.15.2",
    "next": "^2.1.1",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "rollbar": "^0.6.5"
  }
```

I modified one line of your code to
```
-  server.use(rollbar.errorHandler(config.ERROR_REPORTING, { environment: config.NODE_ENV })
+  server.use(rollbar.errorHandler('my post_server_item token', { environment: 'test-next' })
```

I ran `npm install` to get all of the dependencies, then I ran `node index.js` and went to `http://localhost:3000` in my browser. I see the error in the browser and in the terminal. I also see the error properly reported to rollbar on my rollbar dashboard.

Also, the output of `node -v` is `v7.5.0`

**Comment by khrome83** [comment]
looks like the issue was that we were not using the right token. Thank you!
