### ISSUE TITLE
handleError then immediate shutdown should flush all errors

### ISSUE THREAD

**Issue by wvl** [rollbar/node_rollbar#34]
`handleError` is asynchronous, which is not a problem, except that pendingItems doesn't get appended until after the error has been parsed and formatted. Thus, if we experience an error that causes the process to exit, calling `rollbar.shutdown` does not properly flush/send the crashing error.

This is illustrated with this simple script, and a console.log inside `postItems`:

```
var rollbar = require('rollbar');
rollbar.init('TOKEN');

rollbar.handleError(new Error('Illustrate crasher'));

rollbar.shutdown(function() {
  console.log('shutdown, everything should be flushed/posted');
  setTimeout(function() {
    process.exit(0);
  }, 1000);
});
```

```
$ node crasher.js
rollbar::postItems 0
shutdown, everything should be flushed/posted
rollbar::postItems 1
```

This is not obvious, nor is it desired behavior. I would have expected that as soon as you add an error, it is in the pending queue which `shutdown` will flush.

**Comment by coryvirok** [comment]
Good find. This is happening because of the async call to `fs.readFile()` in parser.js.

It appears there's a bug in that code that is calling the callback before all file data is read.

If you want to take a stab at it, please send a PR over. Otherwise, we can get to it soon.

**Comment by whyhankee** [comment]
Got bitten by this one as well :(

A fix would really be appreciated, I tried to 'take a stab at it' but i don't feel confident messing with this part of the code :( Sorry ..

**Comment by coryvirok** [comment]
Hey everyone. Sorry for the delay. I've done some refactoring/bugfixing here - https://github.com/rollbar/node_rollbar/pull/37

I'll plan on merging this early next week so please let me know if you have any feedback.

Thanks!

**Comment by coryvirok** [comment]
Published this fix, (and another this am) to NPM. v0.5.1.
