### ISSUE TITLE
Uncaught exception handler only handles an error once

### ISSUE THREAD

**Issue by ratbeard** [rollbar/node_rollbar#35]
I was wondering why the uncaughtException handler is only registered once [1].  The docs on the rollbar website don't mention this behavior [2], and I would expect a function called `handleUncaughtExceptions` to handle all uncaught exceptions, not just one.  A name like"reportOnCrash" or something like that would make more sense for the current behavior.

I thought while debugging this it might be because winston's uncaught exception handler was clashing w/ rollbar's in my app, which as a point of interest handles multiple uncaught exceptions.

FWI I'm aware of Joyent argues you shouldn't use this feature, though I believe their argument was along the lines of _uncaught exceptions get ignored and lead to more difficult to debug exceptions down the line_ though the fact that I'm configuring rollbar to log the exception means it won't be ignored, and I also won't be breaking all my users websocket connections in production :smiley_cat: 

Thanks!

[1]: https://github.com/rollbar/node_rollbar/blob/master/rollbar.js#L255
[2]: https://rollbar.com/docs/notifier/node_rollbar/#uncaught-exceptions
[3]: https://github.com/winstonjs/winston#handling-uncaught-exceptions-with-winston

**Comment by ratbeard** [comment]
I could just log the error in my own unhandledException handler as a workaround

**Comment by coryvirok** [comment]
You make a good case for not using `once()`. If you send over a PR I can get it merged in asap.
