### ISSUE TITLE
changeHandler removed from notifier but still called from rollbar

### ISSUE THREAD

**Issue by twalling** [rollbar/node_rollbar#38]
I commented on the commit which took this method out. We're getting a maximum call stack size exceeded now because this just keeps throwing an exception over and over.

**Comment by coryvirok** [comment]
Ouch. Thanks for the report. Fixed and pushed to NPM. https://github.com/rollbar/node_rollbar/commit/01d512a2b73b38ef1e31dc2485f482f870f55839
