### ISSUE TITLE
Missing shutdown api

### ISSUE THREAD

**Issue by wvl** [rollbar/node_rollbar#39]
Sorry, I don't understand how the fix for #34 actually fixes the problem. Your api is still asynchronous. So if we have code:

```
var rollbar = require('rollbar');
rollbar.init(rollbarToken);
process.on('uncaughtException', function(err) {
  rollbar.handleError(err);
  process.exit(1);
});
throw new Error('Huh?');
```

Since you removed the `shutdown` method, there's no way to ensure that rollbar is flushed before we exit. So we don't know when the error has actually been submitted properly, and I'm back to setting timeouts and hoping that the error has been flushed, or, managing the accounting of your errors myself.

**Comment by coryvirok** [comment]
There is no more flushing. If you want to make sure you wait until the error was sent to Rollbar, you would put the call to `process.exit(1)

**Comment by coryvirok** [comment]
In general, if you have any outstanding IO node will wait for it to complete before shutting down. The exception is if you call `process.exit()` which will terminate all IO and exit immediately.

Here's a test program that demonstrates:

```js
var fs = require('fs');
fs.writeFile('/tmp/test.txt', 'Hello');
// process.exit(1)
```

Run the code with and without the `process.exit(1)`. You'll find that when `process.exit(1)` is commented out, the file is written before the process exits. When you have it commented in, the file is not written. This is because node waits for outstanding IO to finish unless you kill it with `process.exit(1)`.

**Comment by wvl** [comment]
That's all true. However, in a large server side app, we have multiple connections established so the process never exits. On uncaught exceptions, we log the error, close any open connections, and exit (theoretically, node would exit automatically at this time, but practically, there's often something happening that prevents this, so we use process.exit).

Similarly, we can't use rollbar.handleUncaughtExceptions, because we need to do other things (like closing those connections) before we exit.

Now, since we exit on uncaught exceptions, we can rework our code to wait for the callback on handleError before exiting. However, uncaughtException was just an example to illustrate why I'd like the rollbar.shutdown api back. Consider an error that's thrown from inside the SIGINT handler -- in this case we are actively reporting an error while shutting down, and in this case our error path doesn't know to wait for the rollbar error to flush, and therefore more potential lost error reports.

Your previous api was fine, I just wanted it to work. Now, I have to again, hope that the error has been flushed before our process.exit call, or manage the accounting of error reporting manually. Please do reconsider.

**Comment by brianr** [comment]
@wvl Thanks for the explanation - makes total sense to me.

@coryvirok what's required to make this happen in the current implementation?

**Comment by coryvirok** [comment]
Thanks for the info. I think I understand the problem better. 

If I can rephrase, (Please correct me if I'm wrong):

You want to be sure that Rollbar is not in the process of sending anything before you call `process.exit()` and intentionally kill the process. 

I can re-add an optional `shutdown()` function which will essentially just call the callback when there are no more errors in-transit to Rollbar and not accept any new errors to be reported. While I'm at it, I'll add in a `wait()` function which will do the same thing minus the not accepting new errors. 

How does that sound?

**Comment by bryanlarsen** [comment]
Has there been a resolution to this issue?   We're stuck on a very old version of rollbar for this reason.  I tried upgrading to current and there's no rollbar.shutdown command.

**Comment by rokob** [comment]
This was just merged, hopefully this functionality is what you need. It is documented in the README.
