### ISSUE TITLE
Report to multiple projects

### ISSUE THREAD

**Issue by markandrus** [rollbar/node_rollbar#43]
Right now, it appears you can only create a single Rollbar object using a single token with `rollbar.init`. I'd like to see an alternative constructor/initializer that allows reporting to multiple projects. Or is this feature already enabled but hidden away?

**Comment by coryvirok** [comment]
Good question! This is not yet available but we have plans to implement this. I'll update this thread when we have a better idea at when that will be.

**Comment by ryan-rowland** [comment]
@coryvirok Nudge. https://github.com/rollbar/node_rollbar/issues/45

**Comment by coryvirok** [comment]
Hi @ryan-rowland. As you can tell I've been fairly heads down working on Rollbar so my apologies for the long silence. I just added this to our weekly triage list which we will go over tomorrow and one of us will update this thread with more info.

Until then, take a look at the interface that we have for both the browser JS notifier and the Ruby gem - (https://rollbar.com/docs/notifier/rollbar.js/api) Specifically, these methods:

- `global()`
- `configure()`
- `scope()`
- `uncaughtError()`
- `log()`
  - `debug()`
  - `info()`
  - `warn()` / `warning()`
  - `error()`
  - `critical()`

This is the high-level interface that we are adopting for all of our notifiers. I can go into more detail in the code review.

cc chris@rollbar.com to get this on his radar.

**Comment by rokob** [comment]
I am working on making https://github.com/rollbar/rollbar.js actually work on both the server and in the browser. This issue should be solved in that process because the universal library is planned to be more similar to rollbar.js in that you can have separate instances. The tracking issue for this work is: rollbar/rollbar.js#248
