### ISSUE TITLE
Add 'enabled' config parameter

### ISSUE THREAD

**Issue by Koblaid** [rollbar/node_rollbar#53]
Is there a 'enabled' config parameter for node_rollbar like for rollbar.js (https://github.com/rollbar/rollbar.js#disable-reporting-to-rollbarcom)?

I'd like to disable sending errors to Rollbar while developing without adding an `if` statement to every rollbar call.

I could create a PR if you like.

**Comment by brianr** [comment]
There is not, but we'd be happy to merge a PR that implements this :)

**Comment by razorman8669** [comment]
:+1:

**Comment by jordansexton** [comment]
Can this be closed?

**Comment by Koblaid** [comment]
Yes, it was merged with f3335462ff3c9ff6a3b6e1a6bb7b490a5df783d0.
