### ISSUE TITLE
deploy tracking

### ISSUE THREAD

**Issue by blahed** [rollbar/node_rollbar#57]
Any reason why deploy tracking can't or shouldn't be exposed in the node client?

**Comment by brianr** [comment]
No reason I can think of. We'll be happy to accept a pull request :)

**Comment by blahed** [comment]
Yeah, I took a look at it. Looks like it was initially geared towards items, wouldn't wanna try to shoehorn deploys into it without knowing more.

**Comment by MarkHerhold** [comment]
So I take it this is still not supported?

**Comment by rokob** [comment]
This was just merged, will be in the next release.
