### ISSUE TITLE
API error when exception.name is a number

### ISSUE THREAD

**Issue by bblack** [rollbar/node_rollbar#58]
I'm not sure if this is the right place to post this--would a solution be better implemented on the server side?

The [aws sdk](https://github.com/aws/aws-sdk-js) will throw errors that have a `name` property that is a number equal to an HTTP response code (e.g. `503`). I have no idea why they make it a number instead of a string. While node_rollbar or the rollbar API could cast this to a string, what happens instead is an API error with message `Invalid format. data.body.trace.exception.class number value found, but a string is required.`.

**Comment by zoellner** [comment]
I'm getting a similar error (still investigating why now, probably due to node update to 0.12.7): ```[Rollbar] Received error: Invalid format. data.body.trace.exception.class is missing and it is required.```
Wouldn't it be possible to still transfer the available data to rollbar (with enough details to investigate the problem)

**Comment by GautierThiriez** [comment]
Same problem here...

**Comment by coryvirok** [comment]
This should be fixed in 0.6.3.

**Comment by andreaj8** [comment]
same for me with 0.6.5

**Comment by rokob** [comment]
https://github.com/rollbar/node_rollbar/blob/master/lib/parser.js#L268 is where the class value comes from. It *should* be converted to a string here so this is a bit confusing.
