### ISSUE TITLE
Unhandled promises rejections support

### ISSUE THREAD

**Issue by msokk** [rollbar/node_rollbar#61]
Node v4.0.0 and up fires `unhandledRejection` event.
https://nodejs.org/api/process.html#process_event_unhandledrejection

It would be great to have this supported in Rollbar out of the box.

Similar thing could be done in browser (currently Bluebird and soon Chrome native promises fire the same event on window).

**Comment by coryvirok** [comment]
Great idea. We will get this in soon.

**Comment by syrnick** [comment]
+1
