### ISSUE TITLE
rollbar.reportMessage() can't handle request from Express

### ISSUE THREAD

**Issue by aristidesfl** [rollbar/node_rollbar#68]
```
node_modules/rollbar/lib/notifier.js:191
        if (req.body.hasOwnProperty(k)) {
                     ^

TypeError: req.body.hasOwnProperty is not a function
  at buildRequestData (/Users/user/Work/express/node_modules/rollbar/lib/notifier.js:191:22)
  at addRequestData (/Users/user/Work/express/node_modules/rollbar/lib/notifier.js:208:13)
  at addReqData (/Users/user/Work/express/node_modules/rollbar/lib/notifier.js:272:7)
  at /Users/user/Work/express/node_modules/rollbar/node_modules/async/lib/async.js:699:13
  at iterate (/Users/user/Work/express/node_modules/rollbar/node_modules/async/lib/async.js:256:13)
  at nextTickCallbackWith0Args (node.js:452:9)
  at process._tickCallback (node.js:381:13)
```

```
  "dependencies": {
    "body-parser": "^1.14.2",
    "coffee": "^3.0.3",
    "coinbase": "^2.0.2",
    "express-validator": "^2.18.0",
    "multer": "^1.1.0",
    "rollbar": "^0.5.11",
    "sequelize": "^3.17.3"
  },
```

**Comment by coryvirok** [comment]
Thanks for the bug report. Adding to our sprint.

**Comment by jondeandres** [comment]
@aristidesfl can you tell us which express version are you using and a snippet of code that triggers the rollbar report?

**Comment by jondeandres** [comment]
@aristidesfl hi again, I've been debugging this using two different requests:

`curl -X POST http://localhost:3000/ -d '{"username":"xyz","password":"xyz"}' -H "Content-Type: application/json"`

and

`curl -X POST http://localhost:3000/ -d 'foo=bar&bar=foo' -H 'Content-Type: application/x-www-form-urlencoded'`

It is working correctly in both cases. Could you provide more details/information about the kind of request you are trying to handle? Are you using multer in the endpoint that is failing?

Thanks.

**Comment by jondeandres** [comment]
@aristidesfl I've been reading the [multer](https://github.com/expressjs/multer) code and I found this: https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L27.

This will make the `req.body` object to not have `hasOwnProperty` and will make our notifier to crash. This seems to happen only for multipart requests, can you confirm us that you are using a multipart request when the notifier is failing?

Thanks!

**Comment by aristidesfl** [comment]
@jondeandres I'm using `multer` to read `multipart/form-data`. In my case specifically `form-data`. I'm not receiving any files, not sure if that matters.

**Comment by jondeandres** [comment]
hey @aristidesfl, we've found the cause of this. I've opened a PR https://github.com/rollbar/node_rollbar/pull/72. You can test the branch if you want. We'll merge it probably today.

**Comment by aristidesfl** [comment]
Thank you! After its merged how long until a new release?

**Comment by jondeandres** [comment]
we hope we can release today or tomorrow
