### ISSUE TITLE
Add support for multiple Errors - Trace chain

### ISSUE THREAD

**Issue by lostfields** [rollbar/node_rollbar#77]
What about supporting multiple errors by posting a trace chain to rollbar? When making custom errors you may chain errors in the property innerError. To support that you have to make some changes to method buildErrorData in notifier.js something likes this:

```javascript
function buildErrorData(baseData, err, callback) {
    var errors = [];
    
    do {
        errors.push(err);
    } while((err = err.innerError) !== undefined)

    baseData.body.trace_chain = [];

    var chain = baseData.body.trace_chain;
    async.eachSeries(errors, function(ex, cb) {
        
        parser.parseException(ex, function (e, errData) {
            if (e) {
                if(chain.push(e) == 1) cb(e);
            }
                
            chain.push({
                frames: errData.frames,
                exception: {
                    class: errData['class'],
                    message: errData.message
                }
            });

            cb();
        });

    }, function(err) {  
        if(err) 
            callback(err);

        callback(null); 
    });
}
```

**Comment by lostfields** [comment]
or make it possible to override buildErrorData (expose it by exports?) to make it possible to do custom implementations like this.

**Comment by brianr** [comment]
Thanks @lostfields ! I think this makes sense to support in this library. If you want to send a PR, we'd be happy to review it and get it merged.

**Comment by brianr** [comment]
I believe this is done now via https://github.com/rollbar/node_rollbar/pull/81 . @lostfields does that work for your needs?

**Comment by lostfields** [comment]
yes, of course. thanks for closing it @brianr
