### ISSUE TITLE
allow connecting to api.rollbar.com through a proxy

### ISSUE THREAD

**Issue by RasterBurn** [rollbar/node_rollbar#8]
Right now my server-side errors are not being logged because of a corporate firewall.  We have an http proxy but the library doesn't support using one (or it's not documented).

**Comment by pablote** [comment]
:+1: Same case here, and we really need this. Has this been implemented or are there any plans?

**Comment by brianr** [comment]
@coryvirok can you provide some guidance on where the code changes for this would be?

**Comment by coryvirok** [comment]
We would want to switch to using the request library I linked above and configure it to use an optional proxy. https://github.com/request/request#proxies

The code for this would go here: https://github.com/rollbar/node_rollbar/blob/master/lib/api.js#L64

We will also need to add the new library to package.json

**Comment by syrnick** [comment]
Would it work if you just changed https://github.com/rollbar/node_rollbar/blob/master/lib/api.js#L13 to 
`exports.endpoint = (process.env.ROLLBAR_API_PROXY || 'https://api.rollbar.com') + '/api/' + exports.VERSION + '/';`

**Comment by lehresman** [comment]
Looks like simple proxy support was added in Jan, 2015 with this commit 901b407da42980659320b6be4277156b3f12976b.  Is this sufficient?  If so, I'll add documentation.  Otherwise I'll rework it using @coryvirok's suggested 3rd-party library.

**Comment by lehresman** [comment]
Also note https://github.com/rollbar/node_rollbar/pull/32.  Looks like it was signed off by @coryvirok, so I'll just add documentation.

**Comment by rokob** [comment]
This already exists as @lehresman pointed out and is now documented so closing this.
