### ISSUE TITLE
Problems with installing Rollbar in Webpack project

### ISSUE THREAD

**Issue by bmueller-sykes** [rollbar/node_rollbar#89]
Hi,

I posted a comment to the closed issue #84, but wasn't sure that would be seen, so I'm posting a new issue here with largely the same content.

I'm trying to get Rollbar installed into a webpack/React/ES6-based project. In my package.json file, I've got this reference:

"rollbar": "0.6.2",

...and the install appears to go properly, but then when I run `npm start`, I get the following error trace in the console (some project-specific details masked):

```
ERROR in ./~/rollbar/lib/parser.js
Module not found: Error: Cannot resolve module 'fs' in [myProjectRoot]node_modules/rollbar/lib
 @ ./~/rollbar/lib/parser.js 7:9-22

ERROR in ./~/rollbar/package.json
Module parse failed: [myProjectRoot]node_modules/rollbar/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp.raise ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.semicolon ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1469:73)
    at Parser.pp.parseExpressionStatement ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1994:8)
    at Parser.pp.parseStatement ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1772:188)
    at Parser.pp.parseBlock ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:2009:21)
    at Parser.pp.parseStatement ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1753:19)
    at Parser.pp.parseTopLevel ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1666:21)
    at Parser.parse ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1632:17)
    at Object.parse ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
 @ ./~/rollbar/lib/notifier.js 14:18-44
```

I traced the problem down to the file where I'm invoking Rollbar. I've tried a couple of different permutations, below:

`import rollbar from "rollbar"`
`var Rollbar = require('rollbar')`

Both of those attempts produced the same console error, below:

```
ERROR in ./~/rollbar/lib/parser.js
Module not found: Error: Cannot resolve module 'fs' in /Users/[myProjectPath]/node_modules/rollbar/lib
 @ ./~/rollbar/lib/parser.js 7:9-22

ERROR in ./~/rollbar/package.json
Module parse failed: /Users/[myProjectPath]/node_modules/rollbar/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
```

If I add `node: {fs: "empty}` to my `webpack.config.js` file, then the first error goes away (though I admit I don't understand the consequences of this webpack config instruction), but the second error remains.

**Comment by th3fallen** [comment]
@bmueller-sykes add ```

      {
        test: /\.json$/,
        loader: 'json',
      },
```
to your loaders config in webpack

**Comment by bmueller-sykes** [comment]
Thanks @th3fallen. Any collateral damage to other .json files if that loader is part of the webpack config?

**Comment by th3fallen** [comment]
not that i've encountered you'll need to install `json-loader` from npm though

**Comment by rokob** [comment]
Do you have your target set to `node`? I have an example express app (https://github.com/rokob/expressbar) using webpack to compile both the server and frontend code using separate webpack configs. It builds and runs, includes rollbar, and does not use the json-loader. That said using the json-loader should not be troublesome either.

**Comment by rokob** [comment]
Feel free to reopen if this is still a problem.

**Comment by cordoval** [comment]
wish you could post a solution for those not using backend node, just webpack frontend

**Comment by th3fallen** [comment]
@cordoval use the [rollbar-browser](https://www.npmjs.com/package/rollbar-browser) package

**Comment by cordoval** [comment]
is the same

**Comment by th3fallen** [comment]
@cordoval no it's not i use it in my project just fine.

```
import Rollbar from 'rollbar-browser/dist/rollbar.umd.nojson';
import Environment from 'shared/util/environment';

let rollbarConfig = {
  enabled: !Environment.isDevelopment(),
  accessToken: CONFIG.ROLLBAR_KEY,
  captureUncaught: true,
  captureUnhandledRejections: false,
  payload: {
    environment: CONFIG.ENV || 'dev',
    client: {
      javascript: {
        source_map_enabled: true,
        guess_uncaught_frames: true,
        code_version: CONFIG.DEPLOY.SHA,
      },
    },
  },
  transform: function (obj) {
    const LogRocket = require('logrocket');
    obj.data.sessionURL = LogRocket.sessionURL;
    return obj;
  },
  // Function signature: https://rollbar.com/docs/notifier/rollbar.js/#context-1
  // Payload structure: https://rollbar.com/docs/api/items_post/
  checkIgnore: function (isUncaught, args, payload) {
    try {
      const ignore = payload.data.body.trace.frames.map(frame => {
        const filename = frame.filename;
        return filename.includes('googletagmanager');
      });
      // return true if you wish to ignore this error :facepalm:
      return ignore.includes(true);
    } catch (e) {

    }
  },
};

export default Rollbar.init(rollbarConfig);

```

**Comment by cordoval** [comment]
so that goes inside webpack.config.js before everything else? i think webpack builds the packages differently so i was thinking i needed a plugin or something no?

**Comment by th3fallen** [comment]
that's it's own file, that i import in my project

**Comment by cordoval** [comment]
hmm so it is inserted on each time i need it then on each page?

**Comment by cordoval** [comment]
i have made it its own file but i did not need the -browser part

```
var Rollbar = require('rollbar/dist/rollbar.umd.nojson');
```

**Comment by th3fallen** [comment]
you should need the -browser part....

**Comment by cordoval** [comment]
it fetches the same file though, can you please elaborate why?

**Comment by th3fallen** [comment]
¯\_(ツ)_/¯ if youre sure it's the same file either way then carry on.

**Comment by cordoval** [comment]
sorted it out and it works! 🗡
