### ISSUE TITLE
getting up to par with other rollbar implementations

### ISSUE THREAD

**Issue by jamesdixon** [rollbar/node_rollbar#91]
Hi, it seems that the Node SDK for Rollbar along with some of the other languages is a bit behind the Ruby SDK. Is there a timeline for all the SDKs getting on the same page?

**Comment by jessewgibbs** [comment]
Hi James,
Thanks for bringing this up.  We are planning a major effort during the second half of this year to bring all our the Rollbar-supported notifiers up to the level of the Ruby SDK.  Keep an eye on the changelogs and our blog & email announcements!
