### ISSUE TITLE
CORS issues?

### ISSUE THREAD

**Issue by th3fallen** [rollbar/node_rollbar#93]
When attempting to push an error up i get 
```
XMLHttpRequest cannot load https://api.rollbar.com/api/1/item/. Response to preflight request doesn't pass access control check: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://beta.wheniwork.dev:3000' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.
```
am i missing something?

**Comment by coryvirok** [comment]
Looks like you might want to be using https://github.com/rollbar/rollbar.js for browser error detection/reporting. node_rollbar is meant for server-side only projects.

**Comment by th3fallen** [comment]
@coryvirok im using it in a react/webpack project i assumed this was the appropriate one?

**Comment by coryvirok** [comment]
Gotcha. You should use rollbar.js. Here's an example for how to use it with Webpack - https://github.com/rollbar/rollbar.js/tree/master/examples/webpack

**Comment by th3fallen** [comment]
@coryvirok yep found that a few min ago. works much better. thanks so much
