### ISSUE TITLE
The mask used to hide sensitive params should be fixed length

### ISSUE THREAD

**Issue by lumberj** [rollbar/node_rollbar#98]
See: https://github.com/rollbar/node_rollbar/blob/9576a54075bb60eb61eb26e8240c11c4bacfc043/lib/notifier.js#L181

It's an unnecessary leak of information to have a mask length equal to the length of the data that's being masked.

**Comment by stclairdaniel** [comment]
Thank you for pointing this out. It's on our radar moving forward.

**Comment by rokob** [comment]
Fixed via #105
