### ISSUE TITLE
itemsPerMinute / maxItems global rollbar options

### ISSUE THREAD

**Issue by zdespolit** [rollbar/node_rollbar#99]
Hi, sorry for the question as an issue, but I don't see such options in the api provided. 

Looking for the same availbable on the client
https://rollbar.com/docs/notifier/rollbar.js/configuration/

Am I missing something? Or do you plan to add it?

**Comment by rokob** [comment]
I am working on making https://github.com/rollbar/rollbar.js actually work on both the server and in the browser. These options are available in the browser but not on the server currently, as you point out, but that will be rectified. The tracking issue for this work is: rollbar/rollbar.js#248
